### ISSUE TITLE
升级到1.6.49后使用文件申请zerossl证书验证证书状态时出现

### ISSUE THREAD

**Issue by Paul-George-13** [dromara/domain-admin#135]
![domain](https://github.com/user-attachments/assets/701460b8-90df-4338-86de-dcb9233d199e)

日志：
                                                                     
2024-09-25 11:30:33 [ERROR] handler.py/error_handler:                      
request.path: /api/verifyCertificateById

2024-09-25 11:30:33 [ERROR] handler.py/error_handler:               
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()                                                               
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                         
  File "/app/domain_admin/service/auth_service.py", line 101, in wrapper
    ret = func(*args, **kwargs)                                                                      
  File "/app/domain_admin/api/issue_certificate_api.py", line 72, in verify_certificate
    issue_certificate_service.verify_certificate(issue_certificate_id, challenge_type)                 
  File "/app/domain_admin/service/issue_certificate_service.py", line 158, in verify_certificate
    raise AppException(".....................{}".format(item['domain']))                   
domain_admin.utils.flask_ext.app_exception.AppException

**Comment by Paul-George-13** [comment]
点击服务器部署是可以的，文件可以被放入服务器中

**Comment by Paul-George-13** [comment]
[root@ops-web challenges]# ll
总用量 20
-rw-r--r--. 1 root root 87 9月  25 11:16 TiYaId55pTTCshZSOOI8ulAbMZGFs3IxkH
[root@ops-web challenges]#

**Comment by mouday** [comment]
好的，我排查下

**Comment by Paul-George-13** [comment]
![domain](https://github.com/user-attachments/assets/a0c343c8-6fc6-4fe9-bbf5-5712a907eba3)
debug发现请求这个地址报405错误
